spring:
  dubbo:
    consumer:
      timeout: 3000
      check: false
      application:
        name: mylife
      registry:
        address: zookeeper://39.97.96.131:2181
      protocol:
        name: dubbo
        port: 20889
      server: true
      base-package: com.hello.mylife


debug: false

zookeeper:
  address: 39.97.96.131:2181